models:
  - name: "mistralai/Mistral-7B-v0.1"
    purpose: "general-purpose"
    local_path: "C:/Users/me/.cache/huggingface/hub/models--mistralai--Mistral-7B-v0.1/snapshots/7231864981174d9bee8c7687c24c8344414eae6b"

  - name: "rinna/japanese-gpt2-medium"
    purpose: "japanese-text-generation"
    local_path: "C:/Users/me/.cache/huggingface/hub/models--rinna--japanese-gpt2-medium/snapshots/25640a78ebc4425184bd05f23dbce35bd79fbaaa"

  - name: "gpt2"
    purpose: "english-text-generation"
    local_path: "C:/Users/me/.cache/huggingface/hub/models--gpt2/snapshots/607a30d783dfa663caf39e06633721c8d4cfcd7e"

  - name: "EleutherAI/gpt-neo-1.3B"
    purpose: "gpt-neo"

  - name: "EleutherAI/gpt-j-6B"
    purpose: "gpt-j-6B"

  - name: "meta-llama/Llama-2-7b-hf"
    purpose: "llama-2"
